import { Locale } from "@/lib/i18n/types";
import { AssetLearningPath } from "./types";

type LessonPatch = { title: string; explanation: string; keyTakeaways: string[] };
type QuizPatch = { question: string; options: string[]; explanation: string };
type AssetPatch = { title: string; shortDescription: string; lessons: Record<string, LessonPatch>; quizQuestions: Record<string, QuizPatch> };

const FR: Record<string, AssetPatch> = {
  sp500: { title: "Comprendre le S&P 500", shortDescription: "Ce qu'est un indice boursier et comment fonctionne le S&P 500.", lessons: {
    "what-is-it": { title: "Qu'est-ce que le S&P 500 ?", explanation: "Le S&P 500 est un indice qui suit les actions de 500 des plus grandes entreprises cotées aux États-Unis. Il est l'un des indicateurs les plus utilisés pour suivre le marché actions américain.", keyTakeaways: ["Il suit 500 grandes entreprises américaines.", "C'est un indice, pas une action individuelle."] },
    "companies-inside": { title: "Quelles entreprises le composent ?", explanation: "On y trouve des entreprises de nombreux secteurs : technologie, banques, santé, distribution, énergie et bien d'autres. Il donne ainsi une vue large des grandes entreprises américaines.", keyTakeaways: ["L'indice couvre de nombreux secteurs.", "Les géants technologiques n'en sont qu'une partie."] },
    "how-calculated": { title: "Comment est-il calculé ?", explanation: "L'indice est pondéré par capitalisation boursière : les plus grandes entreprises ont davantage d'influence sur son évolution. Un mouvement important d'Apple a donc plus d'effet qu'un mouvement identique d'une petite entreprise.", keyTakeaways: ["La pondération dépend de la capitalisation boursière.", "Les plus grandes entreprises ont davantage de poids."] },
    "why-price-moves": { title: "Pourquoi son cours évolue-t-il ?", explanation: "Les cours réagissent notamment aux bénéfices des entreprises, aux taux d'intérêt, à l'inflation et au sentiment des investisseurs. Les anticipations de croissance jouent aussi un rôle.", keyTakeaways: ["Bénéfices, taux et inflation peuvent influencer l'indice.", "Les anticipations des investisseurs comptent aussi."] },
    "what-it-represents": { title: "Que représente réellement un indice ?", explanation: "Un indice n'est pas une action que l'on achète directement : c'est une référence. Les investisseurs utilisent généralement un fonds ou un ETF qui cherche à reproduire sa performance.", keyTakeaways: ["Un indice est une référence, pas une action unique.", "Des fonds et ETF peuvent reproduire sa performance."] },
  }, quizQuestions: {
    q1: { question: "Que représente le S&P 500 ?", options: ["Une seule entreprise", "Un groupe de grandes entreprises américaines", "Le prix de l'or", "Le dollar américain"], explanation: "Le S&P 500 suit 500 des plus grandes entreprises américaines." },
    q2: { question: "Comment le S&P 500 est-il pondéré ?", options: ["À parts égales", "Selon l'ancienneté", "Selon la capitalisation boursière", "Par ordre alphabétique"], explanation: "Il est pondéré par capitalisation boursière, donc les grandes entreprises ont davantage d'influence." },
    q3: { question: "Lequel de ces éléments peut faire bouger le S&P 500 ?", options: ["Une variation des taux d'intérêt", "La météo à New York", "La sortie d'un nouvel emoji", "Aucun des choix"], explanation: "Les taux, l'inflation et les bénéfices peuvent influencer les indices." },
    q4: { question: "Peut-on acheter directement le S&P 500 comme une seule action ?", options: ["Oui", "Non, mais des fonds suivent sa performance", "Seules les banques peuvent l'acheter", "Seulement avec de l'or"], explanation: "L'indice lui-même n'est pas une action négociable ; des fonds et ETF peuvent en suivre la performance." },
    q5: { question: "Pourquoi les investisseurs suivent-ils de près le S&P 500 ?", options: ["C'est une référence large du marché actions américain", "Il ne suit qu'un secteur", "Il garantit des bénéfices", "Sa valeur ne change jamais"], explanation: "Il couvre de nombreux secteurs et grandes entreprises et sert donc de référence du marché." },
  } },
  nasdaq: { title: "Comprendre le Nasdaq 100", shortDescription: "Un indice orienté technologie et croissance, et ses différences avec le S&P 500.", lessons: {
    "nasdaq-what-it-is": { title: "Que représente le Nasdaq 100 ?", explanation: "Le Nasdaq 100 suit 100 des plus grandes entreprises non financières cotées au Nasdaq. Il est fortement exposé à la technologie et à la croissance : logiciels, semi-conducteurs, plateformes internet et technologie grand public.", keyTakeaways: ["100 grandes entreprises non financières du Nasdaq.", "Forte exposition à la technologie et à la croissance.", "Les entreprises financières sont exclues."] },
    "nasdaq-concentration": { title: "Concentration, croissance et volatilité", explanation: "Comme le S&P 500, le Nasdaq 100 est pondéré par capitalisation, mais sa liste plus étroite et sa concentration sectorielle donnent davantage de poids à quelques grandes entreprises. Leurs résultats peuvent donc provoquer des mouvements plus marqués.", keyTakeaways: ["Pondéré par capitalisation comme le S&P 500.", "Moins de secteurs signifie davantage de concentration.", "La concentration peut amplifier les mouvements."] },
    "nasdaq-vs-sp500": { title: "En quoi diffère-t-il du S&P 500 ?", explanation: "Le S&P 500 couvre presque tous les secteurs de l'économie américaine, tandis que le Nasdaq 100 est plus concentré dans la technologie et la croissance et exclut les financières. Il peut donc réagir davantage aux taux et aux nouvelles technologiques.", keyTakeaways: ["S&P 500 plus large ; Nasdaq 100 plus concentré en tech/growth.", "Le Nasdaq 100 réagit souvent davantage aux taux et aux nouvelles tech.", "Ils représentent des segments différents du marché."] },
  }, quizQuestions: {
    "nasdaq-q1": { question: "Que suit principalement le Nasdaq 100 ?", options: ["100 des plus grandes entreprises non financières du Nasdaq", "Toutes les entreprises du Nasdaq", "Uniquement des startups tech", "Des obligations américaines"], explanation: "Il s'agit d'une sélection de 100 grandes entreprises non financières cotées au Nasdaq." },
    "nasdaq-q2": { question: "Quel type d'entreprise est exclu du Nasdaq 100 ?", options: ["Les entreprises technologiques", "Les entreprises financières", "Les entreprises de consommation", "Les entreprises de santé"], explanation: "Les entreprises financières sont exclues de l'indice." },
    "nasdaq-q3": { question: "Pourquoi le Nasdaq 100 peut-il être plus concentré que le S&P 500 ?", options: ["Il couvre moins de secteurs et une liste plus étroite", "Il ne comprend qu'une entreprise", "Les 100 entreprises ont le même poids", "Il exclut les grandes entreprises"], explanation: "Sa composition plus étroite permet aux grandes positions d'avoir davantage de poids." },
    "nasdaq-q4": { question: "Si plusieurs grandes entreprises du Nasdaq 100 publient de faibles bénéfices, quel effet est probable ?", options: ["Aucun", "Un mouvement potentiellement important", "Aucun effet des bénéfices", "Seules les financières réagissent"], explanation: "Les plus grandes positions ont davantage de poids et peuvent déplacer l'indice." },
    "nasdaq-q5": { question: "Quelle comparaison décrit le mieux le Nasdaq 100 et le S&P 500 ?", options: ["Ils suivent les mêmes entreprises", "Le Nasdaq 100 est plus large", "Le Nasdaq 100 est plus concentré en tech/growth ; le S&P 500 couvre plus de secteurs", "Le S&P 500 exclut les financières"], explanation: "Le Nasdaq 100 est concentré en tech/growth, tandis que le S&P 500 couvre presque tous les secteurs." },
    "nasdaq-q6": { question: "Pourquoi le Nasdaq 100 peut-il réagir plus fortement aux taux ?", options: ["Il ne contient que des obligations", "Les valorisations des entreprises de croissance sont plus sensibles à l'actualisation des bénéfices futurs", "Il n'a aucun lien avec l'économie", "Les taux n'affectent pas les indices"], explanation: "Les indices orientés croissance sont souvent plus sensibles au taux d'actualisation." },
  } },
  aapl: { title: "Comprendre Apple Inc.", shortDescription: "Comment détenir une entreprise comme Apple diffère de détenir un indice.", lessons: {
    "aapl-business-model": { title: "Le modèle économique d'Apple", explanation: "Apple vend des appareils comme l'iPhone, le Mac, l'iPad et l'Apple Watch, et développe des revenus récurrents avec l'App Store, iCloud, Apple Music et d'autres abonnements. Le matériel crée l'écosystème ; les services prolongent la relation avec le client.", keyTakeaways: ["Le matériel représente une part essentielle des revenus.", "Les services apportent des revenus récurrents.", "Matériel et services se renforcent mutuellement."] },
    "aapl-earnings-valuation": { title: "Chiffre d'affaires, bénéfices et valorisation", explanation: "Apple publie chaque trimestre son chiffre d'affaires et ses bénéfices. Les investisseurs les comparent aux attentes : un résultat en hausse peut décevoir s'il est inférieur à ce que le marché anticipait. Le cours reflète aussi les attentes concernant les bénéfices futurs.", keyTakeaways: ["Le chiffre d'affaires correspond aux ventes ; le bénéfice tient compte des coûts.", "Le marché compare les résultats aux attentes.", "Le cours reflète aussi les bénéfices futurs attendus."] },
    "aapl-company-risk": { title: "Risque propre à l'entreprise", explanation: "Avec un indice, les problèmes d'une entreprise sont dilués parmi beaucoup d'autres. Avec Apple seule, l'investisseur est exposé aux risques liés aux produits, à la chaîne d'approvisionnement, à la réglementation ou à la demande.", keyTakeaways: ["Une action individuelle porte des risques spécifiques.", "Produits, approvisionnement et réglementation sont des exemples.", "La concentration peut amplifier les gains comme les pertes."] },
  }, quizQuestions: {
    "aapl-q1": { question: "Quelles sont les deux grandes catégories de revenus d'Apple ?", options: ["Matériel et services", "Publicité et commerce", "Extraction et industrie", "Prêts et assurance"], explanation: "Apple gagne de l'argent grâce au matériel et aux services." },
    "aapl-q2": { question: "Lequel est un exemple de revenu de services d'Apple ?", options: ["Ventes d'iPhone", "Abonnements App Store et iCloud", "Ventes de Mac", "Loyer des magasins"], explanation: "App Store et iCloud génèrent des revenus récurrents de services." },
    "aapl-q3": { question: "Pourquoi une action peut-elle baisser malgré une hausse du bénéfice ?", options: ["Une hausse du bénéfice fait toujours monter l'action", "Le résultat peut être inférieur aux attentes du marché", "Le bénéfice n'a aucun lien avec le cours", "Une action ne peut pas baisser après une hausse du bénéfice"], explanation: "Le marché réagit aux résultats par rapport aux attentes déjà intégrées au cours." },
    "aapl-q4": { question: "Que représente approximativement la valorisation d'une action ?", options: ["Le nombre d'employés", "Ce que les investisseurs acceptent de payer aujourd'hui pour des bénéfices futurs", "Le siège de l'entreprise", "Un cours futur garanti"], explanation: "La valorisation reflète ce que le marché accepte de payer pour les performances futures attendues." },
    "aapl-q5": { question: "Pourquoi une seule action Apple est-elle généralement plus risquée qu'un indice large ?", options: ["Les actions individuelles sont toujours plus chères", "Les événements propres à Apple ne sont pas dilués parmi d'autres entreprises", "Les indices ne peuvent pas perdre de valeur", "Apple n'a pas de concurrents"], explanation: "Les problèmes d'une seule entreprise touchent directement cette action, contrairement à un indice diversifié." },
    "aapl-q6": { question: "Quel scénario illustre le mieux un risque propre à Apple ?", options: ["Une variation générale des taux", "Une rupture d'approvisionnement sur un produit", "Toutes les actions du S&P 500 montent", "Un jour férié mondial"], explanation: "Un problème d'approvisionnement sur une gamme Apple est spécifique à l'entreprise." },
  } },
  nvda: { title: "Comprendre NVIDIA Corp.", shortDescription: "GPU, infrastructure IA et risques d'une action à forte croissance et fortes attentes.", lessons: {
    "nvda-gpus-ai": { title: "GPU et infrastructure IA", explanation: "NVIDIA conçoit des GPU, initialement créés pour le rendu graphique. Leur architecture convient aux calculs parallèles nécessaires à l'entraînement et à l'exécution des modèles d'IA, ce qui en fait une brique importante des centres de données modernes.", keyTakeaways: ["Les GPU sont le produit central de NVIDIA.", "Leur architecture convient aux calculs parallèles de l'IA.", "Les logiciels autour des GPU comptent aussi."] },
    "nvda-cycle-competition": { title: "Centres de données, cycle des semi-conducteurs et concurrence", explanation: "La demande de puces NVIDIA dépend fortement des dépenses des grandes entreprises technologiques dans les centres de données. Le secteur des semi-conducteurs est cyclique et NVIDIA fait face à d'autres fabricants ainsi qu'à des clients qui développent leurs propres puces.", keyTakeaways: ["La demande est concentrée chez de grands clients.", "Les semi-conducteurs sont historiquement cycliques.", "La concurrence vient des fabricants et des clients."] },
    "nvda-expectation-risk": { title: "Forte croissance et fortes attentes", explanation: "Quand le cours intègre déjà une forte croissance future, un bon trimestre qui ne fait que répondre aux attentes peut décevoir le marché. Cela rend les actions à forte croissance sensibles aux mauvaises surprises.", keyTakeaways: ["De fortes attentes peuvent transformer de bons résultats en déception.", "Une partie de la valeur dépend des hypothèses futures.", "Ce phénomène concerne de nombreuses entreprises de croissance."] },
  }, quizQuestions: {
    "nvda-q1": { question: "À quoi la technologie GPU de NVIDIA était-elle destinée à l'origine ?", options: ["Au rendu graphique des jeux vidéo", "À l'extraction de métaux", "Aux tableurs", "Aux véhicules électriques"], explanation: "Les GPU ont d'abord été conçus pour le rendu graphique avant de devenir centraux pour l'IA." },
    "nvda-q2": { question: "Pourquoi les GPU conviennent-ils bien aux charges de travail d'IA ?", options: ["Leur architecture gère les calculs parallèles nécessaires", "Ce sont toujours les puces les moins chères", "Ils ont été conçus uniquement pour l'IA", "Ils ne consomment pas d'électricité"], explanation: "L'architecture des GPU correspond aux calculs parallèles utilisés par les modèles d'IA." },
    "nvda-q3": { question: "Qu'est-ce qui pourrait ralentir la demande de puces NVIDIA ?", options: ["De grands clients réduisant leurs dépenses de centres de données", "Rien", "Les GPU devenant illégaux", "Une hausse du prix de l'or"], explanation: "Les dépenses des grands clients peuvent ralentir." },
    "nvda-q4": { question: "Qu'est-ce qui caractérise historiquement l'industrie des semi-conducteurs ?", options: ["Une demande parfaitement stable", "Des cycles de forte demande suivis de surcapacités", "Aucune concurrence", "Une croissance garantie"], explanation: "Le secteur connaît historiquement des cycles de demande forte puis de surcapacités." },
    "nvda-q5": { question: "Pourquoi une action peut-elle baisser malgré une forte croissance ?", options: ["La croissance garantit toujours une hausse", "Si elle ne dépasse pas des attentes très élevées, elle peut décevoir", "La croissance n'a aucun lien avec le cours", "Les actions réagissent seulement aux pertes"], explanation: "Avec des attentes élevées, simplement les atteindre peut être insuffisant." },
    "nvda-q6": { question: "De quoi dépend souvent une grande partie de la valorisation d'une entreprise à forte croissance ?", options: ["Uniquement des résultats passés", "Des hypothèses de croissance future", "De l'emplacement des bureaux", "De rien"], explanation: "Les valorisations de croissance intègrent fortement les attentes futures." },
  } },
  tsla: { title: "Comprendre Tesla Inc.", shortDescription: "Véhicules électriques, énergie, attentes de croissance et volatilité de l'action.", lessons: {
    "tsla-business-segments": { title: "Véhicules électriques et autres activités", explanation: "L'activité principale de Tesla consiste à concevoir, fabriquer et vendre des véhicules électriques. L'entreprise possède aussi une activité de production et stockage d'énergie et communique sur la robotique et la conduite autonome.", keyTakeaways: ["Les véhicules électriques constituent l'activité principale.", "L'énergie et le stockage sont des activités plus petites.", "L'autonomie et la robotique influencent les attentes."] },
    "tsla-growth-competition": { title: "Attentes de croissance et concurrence", explanation: "Une partie de la valorisation de Tesla reflète des attentes de croissance rapide. En parallèle, la concurrence sur les véhicules électriques augmente et exerce une pression sur les prix et les parts de marché.", keyTakeaways: ["La valorisation dépend fortement des attentes de croissance.", "La concurrence dans les véhicules électriques augmente.", "Les livraisons et les marges sont suivies de près."] },
    "tsla-volatility": { title: "Pourquoi l'action est-elle volatile ?", explanation: "Tesla a historiquement connu des mouvements plus importants que le marché. Les attentes élevées, les déclarations publiques du dirigeant, les livraisons, les marges et les paris sur des activités futures peuvent amplifier les réactions aux nouvelles.", keyTakeaways: ["Les attentes élevées amplifient les réactions aux nouvelles.", "Livraisons et marges peuvent provoquer de forts mouvements.", "Une partie de la valorisation repose sur des activités futures incertaines."] },
  }, quizQuestions: {
    "tsla-q1": { question: "Quel est le principal segment de revenus de Tesla ?", options: ["Les véhicules électriques", "L'assurance", "Le cloud computing", "La banque"], explanation: "Les véhicules électriques représentent la majorité des revenus actuels." },
    "tsla-q2": { question: "Lequel fait partie de l'activité énergie de Tesla ?", options: ["Powerwall et Megapack", "Un service bancaire", "Un réseau social", "Un moteur de recherche"], explanation: "Powerwall et Megapack sont des systèmes de stockage d'énergie." },
    "tsla-q3": { question: "Qu'est-ce qui a fortement augmenté sur le marché des véhicules électriques ?", options: ["La concurrence", "La garantie de bénéfices", "La disparition des autres constructeurs", "La stabilité des parts de marché"], explanation: "Les constructeurs historiques et les nouveaux entrants ont accru la concurrence." },
    "tsla-q4": { question: "Pourquoi les investisseurs suivent-ils les livraisons trimestrielles ?", options: ["Elles donnent un signal sur la trajectoire de croissance", "Elles n'ont aucun lien avec l'activité", "Elles concernent seulement les banques", "Elles déterminent les taux"], explanation: "Les livraisons indiquent si les attentes de croissance se réalisent." },
    "tsla-q5": { question: "Pourquoi des attentes de croissance élevées peuvent-elles rendre une action plus volatile ?", options: ["Elles amplifient la réaction aux nouvelles", "Elles garantissent que l'action ne baisse jamais", "Elles éliminent le risque", "Elles n'ont aucun effet"], explanation: "Lorsque la croissance est déjà intégrée au prix, les nouvelles peuvent provoquer de plus grands mouvements." },
    "tsla-q6": { question: "Que signifie qu'une partie de la valorisation reflète des activités futures non prouvées ?", options: ["Le cours reflète seulement les ventes actuelles", "Une partie du cours repose sur des attentes concernant des activités futures", "Tesla n'a aucun projet futur", "Le succès futur est garanti"], explanation: "Une partie de la valorisation dépend de résultats futurs incertains." },
  } },
  msft: { title: "Comprendre Microsoft Corp.", shortDescription: "Logiciels, cloud Azure, revenus récurrents et exposition à l'IA.", lessons: {
    "msft-software-cloud": { title: "Logiciels et activité cloud", explanation: "Microsoft combine des logiciels comme Windows et Office avec Azure, sa plateforme cloud. Son activité associe logiciels, services et infrastructure, avec une forte clientèle professionnelle.", keyTakeaways: ["Microsoft combine logiciels, services et cloud.", "Azure est une activité majeure de cloud.", "Les entreprises sont une clientèle importante."] },
    "msft-recurring-revenue": { title: "Revenus récurrents et pourquoi ils comptent", explanation: "Les abonnements à Microsoft 365 et à d'autres services génèrent des paiements réguliers. Cette structure peut rendre les revenus plus prévisibles qu'une vente ponctuelle, sans éliminer les risques.", keyTakeaways: ["Les abonnements créent des revenus récurrents.", "Ils peuvent rendre les revenus plus prévisibles.", "La prévisibilité n'élimine pas le risque."] },
    "msft-ai-competition": { title: "IA, valorisation et concurrence", explanation: "Microsoft investit fortement dans l'IA et l'intègre à ses produits et au cloud. Ces investissements peuvent soutenir la croissance mais nécessitent des dépenses importantes et se font dans un environnement concurrentiel.", keyTakeaways: ["L'IA est intégrée aux produits et au cloud.", "L'IA nécessite des investissements importants.", "La concurrence influence les résultats futurs."] },
  }, quizQuestions: {
    "msft-q1": { question: "Quel était le modèle économique historique de Microsoft ?", options: ["Vendre des logiciels comme Windows et Office", "Vendre du pétrole", "Exploiter des hôtels", "Fabriquer des voitures"], explanation: "Microsoft s'est historiquement développé grâce à la vente de logiciels." },
    "msft-q2": { question: "Qu'est-ce qu'Azure ?", options: ["La plateforme cloud de Microsoft", "Un réseau social", "Un constructeur automobile", "Une banque"], explanation: "Azure est la plateforme de cloud computing de Microsoft." },
    "msft-q3": { question: "Pourquoi les revenus récurrents sont-ils souvent plus prévisibles ?", options: ["Les abonnements génèrent des paiements réguliers", "Ils garantissent une hausse des bénéfices", "Ils ne dépendent jamais des clients", "Ils éliminent la concurrence"], explanation: "Les abonnements apportent des paiements réguliers, ce qui peut rendre les revenus plus prévisibles." },
    "msft-q4": { question: "Comment Office a-t-il fait évoluer son modèle de revenus ?", options: ["Vers davantage d'abonnements récurrents", "Vers la vente de pétrole", "Vers une banque en ligne", "Il a supprimé tout paiement"], explanation: "Office s'est largement orienté vers les abonnements Microsoft 365." },
    "msft-q5": { question: "Quel est un coût réel lié aux investissements de Microsoft dans l'IA ?", options: ["Les dépenses en centres de données, puces et infrastructure", "Aucun coût", "Uniquement la publicité", "Les magasins physiques"], explanation: "L'IA nécessite des investissements en centres de données, puces, énergie et infrastructure." },
    "msft-q6": { question: "Que reflète le cours d'une action concernant les investissements dans l'IA ?", options: ["Les attentes concernant les bénéfices futurs", "Uniquement les bénéfices passés", "La localisation des bureaux", "Un prix futur garanti"], explanation: "Le cours peut intégrer des attentes concernant les revenus et bénéfices futurs de l'IA." },
  } },
  amzn: { title: "Comprendre Amazon.com Inc.", shortDescription: "E-commerce, AWS, publicité, marges et risques d'exécution.", lessons: {
    "amzn-ecommerce-aws": { title: "E-commerce et AWS", explanation: "Amazon combine une immense activité de commerce en ligne et AWS, sa plateforme cloud. Le commerce génère beaucoup de chiffre d'affaires avec des marges relativement faibles, tandis qu'AWS a un profil économique différent.", keyTakeaways: ["Amazon combine commerce en ligne et cloud.", "AWS est la plateforme cloud d'Amazon.", "Les deux activités ont des profils de marge différents."] },
    "amzn-advertising-margins": { title: "Publicité et marges", explanation: "Amazon vend de la publicité aux marques qui souhaitent atteindre des acheteurs. Cette activité peut avoir des marges différentes du commerce, c'est pourquoi les investisseurs suivent la composition du chiffre d'affaires et les marges.", keyTakeaways: ["La publicité complète le commerce et le cloud.", "Les activités ont des marges différentes.", "La composition de la croissance compte."] },
    "amzn-execution-risk": { title: "Croissance et risque d'exécution", explanation: "Amazon investit dans plusieurs activités et doit contrôler les coûts tout en exécutant efficacement ses plans. Le risque d'exécution correspond à la possibilité que les décisions et investissements ne produisent pas les résultats attendus.", keyTakeaways: ["Amazon gère plusieurs activités différentes.", "Les investissements doivent être bien exécutés.", "Les coûts et marges sont importants."] },
  }, quizQuestions: {
    "amzn-q1": { question: "Qu'est-ce qu'AWS ?", options: ["La plateforme cloud d'Amazon", "Le réseau social d'Amazon", "Une banque", "Une compagnie pétrolière"], explanation: "AWS est l'activité de cloud computing d'Amazon." },
    "amzn-q2": { question: "Pourquoi le commerce en ligne est-il généralement une activité à faible marge ?", options: ["La logistique, les stocks et la concurrence pèsent sur les marges", "Les clients ne paient jamais", "Les ventes en ligne n'ont aucun coût", "Les marges sont garanties"], explanation: "Logistique, livraison, stocks et concurrence rendent le commerce de détail coûteux." },
    "amzn-q3": { question: "Comment la publicité d'Amazon est-elle liée au commerce ?", options: ["Les marques paient pour atteindre des acheteurs sur la plateforme", "Elle remplace le commerce", "Elle n'a aucun lien avec les clients", "Elle ne peut être utilisée que par AWS"], explanation: "La publicité utilise l'audience et l'intention d'achat de la plateforme." },
    "amzn-q4": { question: "Pourquoi regarder la composition des activités d'Amazon ?", options: ["Les activités ont des marges et profils économiques différents", "Elles ont toutes la même marge", "Le chiffre d'affaires n'a aucune importance", "AWS et le commerce sont identiques"], explanation: "La même croissance de chiffre d'affaires peut produire des résultats différents selon la marge." },
    "amzn-q5": { question: "Que signifie « risque d'exécution » chez Amazon ?", options: ["Le risque que les décisions et investissements ne produisent pas les résultats attendus", "Un risque uniquement boursier", "L'absence de concurrence", "Une garantie de croissance"], explanation: "Il concerne la capacité à transformer les investissements et décisions opérationnelles en résultats." },
    "amzn-q6": { question: "Pourquoi un ralentissement d'AWS peut-il être important pour Amazon ?", options: ["AWS est une activité majeure avec une économie différente du commerce", "AWS ne fait pas partie du groupe", "AWS fixe les taux", "AWS ne génère aucun revenu"], explanation: "AWS est une activité importante et son évolution peut affecter significativement les résultats du groupe." },
  } },
  googl: { title: "Comprendre Alphabet (Google)", shortDescription: "Recherche, publicité YouTube, cloud, IA et risques réglementaires.", lessons: {
    "googl-search-youtube": { title: "Recherche, publicité et YouTube", explanation: "Google Search et YouTube attirent une audience massive et permettent à Alphabet de vendre de la publicité. La demande dépend notamment de l'économie, du comportement des utilisateurs et de la valeur des audiences publicitaires.", keyTakeaways: ["La publicité représente une grande partie des revenus.", "Search et YouTube sont des plateformes publicitaires majeures.", "La demande dépend de l'économie et de l'engagement."] },
    "googl-cloud-ai": { title: "Cloud et IA", explanation: "Google Cloud fournit des services informatiques aux entreprises et l'IA est intégrée à de nombreux produits d'Alphabet. L'IA nécessite des centres de données, des puces et de la recherche, mais ouvre aussi de nouvelles possibilités.", keyTakeaways: ["Google Cloud fournit des services aux entreprises.", "L'IA est intégrée à de nombreux produits.", "L'IA nécessite des investissements importants."] },
    "googl-regulation-competition": { title: "Réglementation et concurrence", explanation: "Alphabet fait face à une surveillance concernant la concurrence, la publicité, les données et la recherche en ligne. De nouvelles formes de concurrence, notamment les assistants IA, peuvent aussi changer la façon dont les utilisateurs recherchent l'information.", keyTakeaways: ["Alphabet fait face à une surveillance antitrust.", "Les règles sur les données et la publicité comptent.", "L'IA peut changer la recherche d'information."] },
  }, quizQuestions: {
    "googl-q1": { question: "Quelle est la principale source de revenus d'Alphabet ?", options: ["La publicité", "La vente de voitures", "Les prêts bancaires", "L'extraction minière"], explanation: "La publicité, notamment autour de Search et YouTube, représente la majeure partie des revenus." },
    "googl-q2": { question: "Qu'est-ce qui stimule la demande des annonceurs sur Search et YouTube ?", options: ["L'audience, l'intention des utilisateurs et l'activité économique", "Uniquement le prix de l'or", "Les taux des banques centrales", "La production de pétrole"], explanation: "Les annonceurs recherchent l'accès à une audience et à des utilisateurs intéressés par leurs offres." },
    "googl-q3": { question: "Avec quelles deux entreprises Google Cloud est-il principalement en concurrence ?", options: ["Amazon Web Services et Microsoft Azure", "Apple et Tesla", "Visa et Mastercard", "Shell et BP"], explanation: "Google Cloud est notamment en concurrence avec AWS et Microsoft Azure." },
    "googl-q4": { question: "Quel est un coût réel des investissements d'Alphabet dans l'IA ?", options: ["Les centres de données, les puces et la recherche", "Aucun coût", "Uniquement des bureaux", "Les dividendes des banques"], explanation: "L'IA nécessite des investissements importants en infrastructure, calcul et recherche." },
    "googl-q5": { question: "Pourquoi Alphabet fait-il l'objet d'une forte surveillance réglementaire ?", options: ["Sa position dans la recherche, la publicité et les plateformes soulève des questions de concurrence et de données", "Il ne possède aucun produit", "La réglementation ne s'applique pas à la tech", "Il ne fait pas de publicité"], explanation: "La taille et la position d'Alphabet attirent une surveillance antitrust et réglementaire." },
    "googl-q6": { question: "Quelle concurrence émergente pourrait modifier l'usage de Google Search ?", options: ["Les assistants et moteurs de recherche basés sur l'IA", "Les magasins de vêtements", "Les banques centrales", "Les compagnies pétrolières"], explanation: "Les interfaces de recherche et assistants basés sur l'IA peuvent modifier la façon de trouver l'information." },
  } },
  meta: { title: "Comprendre Meta Platforms", shortDescription: "Publicité, réseaux sociaux, IA, Reality Labs et risques réglementaires.", lessons: {
    "meta-advertising-platforms": { title: "Publicité et plateformes sociales", explanation: "Meta possède Facebook, Instagram et WhatsApp et tire la grande majorité de ses revenus de la publicité. Les entreprises paient pour toucher l'audience de Meta, donc les budgets publicitaires et l'engagement influencent les résultats.", keyTakeaways: ["Facebook, Instagram et WhatsApp sont les principales plateformes.", "La grande majorité des revenus vient de la publicité.", "Les dépenses publicitaires et l'engagement comptent."] },
    "meta-ai-reality-labs": { title: "IA et Reality Labs", explanation: "Meta investit dans l'IA pour la publicité, les recommandations et ses modèles. Reality Labs développe des produits VR/AR et représente un pari de long terme qui a historiquement généré des pertes financées par la publicité.", keyTakeaways: ["L'IA soutient les produits et la recherche.", "Reality Labs est un pari VR/AR de long terme.", "La publicité finance historiquement Reality Labs."] },
    "meta-regulatory-execution-risk": { title: "Réglementation et risque d'exécution", explanation: "Meta fait face à des questions de confidentialité, de concurrence et de modération des contenus. Elle doit aussi équilibrer des investissements coûteux dans des activités incertaines avec la rentabilité de sa publicité.", keyTakeaways: ["Risques liés aux données, à la concurrence et aux contenus.", "Plusieurs grandes plateformes attirent l'attention antitrust.", "Financer des paris coûteux tout en protégeant la rentabilité est un défi."] },
  }, quizQuestions: {
    "meta-q1": { question: "Quelles plateformes Meta possède-t-il ?", options: ["Facebook, Instagram et WhatsApp", "YouTube et Gmail", "Amazon et AWS", "Netflix et Spotify"], explanation: "Facebook, Instagram et WhatsApp sont des plateformes principales de Meta." },
    "meta-q2": { question: "Quelle est la principale source de revenus de Meta ?", options: ["La publicité", "La vente de matériel", "Les abonnements Facebook", "Les magasins physiques"], explanation: "La grande majorité des revenus de Meta provient de la publicité." },
    "meta-q3": { question: "Qu'est-ce que Reality Labs ?", options: ["La division VR/AR de Meta", "L'équipe publicitaire", "Un service de livraison", "Un produit cloud"], explanation: "Reality Labs développe du matériel et des logiciels de réalité virtuelle et augmentée." },
    "meta-q4": { question: "Comment Reality Labs a-t-il historiquement été financé ?", options: ["Par les bénéfices de la publicité de Meta", "Il a toujours été rentable seul", "Par des subventions publiques", "Il ne nécessite aucun financement"], explanation: "Reality Labs a historiquement fonctionné à perte et a été financé par l'activité publicitaire." },
    "meta-q5": { question: "Pourquoi Meta fait-il l'objet d'une attention antitrust particulière ?", options: ["Il possède plusieurs grandes plateformes sociales", "Il ne possède aucun produit important", "Le droit antitrust ne s'applique pas à la technologie", "Il n'opère que sur un petit marché"], explanation: "Le fait de posséder plusieurs grandes plateformes attire une attention particulière sur la concurrence." },
    "meta-q6": { question: "Quel défi d'exécution Meta rencontre-t-il avec Reality Labs ?", options: ["Équilibrer l'investissement dans une activité non prouvée avec la rentabilité publicitaire", "Reality Labs ne nécessite aucune décision", "Il n'existe aucune tension entre les dépenses", "Meta a arrêté tout investissement"], explanation: "Financer une activité coûteuse et incertaine tout en protégeant la rentabilité est un arbitrage important." },
  } },
  gold: { title: "Comprendre l'or", shortDescription: "Ce que représente l'or, les taux réels et pourquoi il ne produit pas de bénéfices.", lessons: {
    "gold-what-it-represents": { title: "Ce que représente l'or comme investissement", explanation: "L'or est une matière première et un actif monétaire utilisé comme réserve de valeur. Contrairement à une action, il ne représente pas une participation dans une entreprise et ne génère pas de flux de trésorerie propres.", keyTakeaways: ["L'or est une matière première, pas une action.", "Il ne produit pas de flux de trésorerie propres.", "L'exposition peut être obtenue directement ou via des produits financiers."] },
    "gold-inflation-real-rates": { title: "Inflation, taux réels et demande refuge", explanation: "L'attrait de l'or peut évoluer avec l'inflation, les taux réels et les périodes de stress économique ou géopolitique. Des taux réels faibles réduisent le coût d'opportunité d'un actif sans rendement. Cela ne garantit toutefois pas une hausse.", keyTakeaways: ["Les taux réels influencent l'attrait relatif de l'or.", "L'or peut être recherché en période de stress.", "Ces relations ne garantissent pas une hausse."] },
    "gold-no-earnings": { title: "Pas de bénéfices ni de dividendes", explanation: "L'or ne génère ni bénéfices, ni dividendes, ni intérêts. Le rendement dépend donc du changement de son prix. C'est une différence structurelle avec les actions et obligations qui peuvent générer des revenus.", keyTakeaways: ["L'or ne verse ni dividendes ni intérêts.", "Le résultat dépend du prix de l'or.", "C'est une différence structurelle avec actions et obligations."] },
  }, quizQuestions: {
    "gold-q1": { question: "L'or verse-t-il des dividendes ?", options: ["Non", "Oui, chaque trimestre", "Oui, seulement aux grands investisseurs", "Uniquement pendant les récessions"], explanation: "L'or ne verse pas de dividendes." },
    "gold-q2": { question: "Quelle est une façon courante d'investir dans l'or ?", options: ["Un ETF qui suit le prix de l'or", "Un compte courant", "Une obligation d'entreprise", "Un bien immobilier locatif"], explanation: "Les ETF qui suivent le prix de l'or sont un moyen courant d'obtenir une exposition." },
    "gold-q3": { question: "Que peut-il arriver à l'attrait de l'or lorsque les taux réels sont faibles ou négatifs ?", options: ["Il peut devenir relativement plus attractif", "Il devient toujours sans valeur", "Il n'existe aucun lien avec les taux", "Il verse automatiquement un dividende"], explanation: "Des taux réels faibles réduisent le coût d'opportunité d'un actif sans rendement." },
    "gold-q4": { question: "Que signifie la « demande refuge » pour l'or ?", options: ["Des investisseurs se tournent vers l'or pendant des périodes de stress", "Une garantie que l'or monte toujours en crise", "Uniquement l'or en bijouterie", "Une obligation gouvernementale d'acheter de l'or"], explanation: "Certains investisseurs recherchent l'or pendant les périodes de stress, sans garantie de hausse." },
    "gold-q5": { question: "Puisque l'or ne produit pas de revenu, de quoi dépend le rendement ?", options: ["De l'évolution du prix de l'or", "De dividendes trimestriels", "D'intérêts versés par l'or", "Des bénéfices d'une entreprise"], explanation: "Sans revenu, le rendement vient de la hausse ou de la baisse du prix." },
    "gold-q6": { question: "Comment l'absence de revenu de l'or se compare-t-elle à une action ou une obligation ?", options: ["Actions et obligations peuvent générer des revenus même si le prix ne bouge pas ; pas l'or", "L'or génère plus de revenus", "Actions et obligations ne génèrent aucun revenu", "Il n'y a aucune différence"], explanation: "Les actions peuvent verser des dividendes et les obligations des intérêts indépendamment du mouvement de prix." },
  } },
  "brent-oil": { title: "Comprendre le pétrole Brent", shortDescription: "Prix mondial du pétrole, offre et demande, et volatilité d'une matière première majeure.", lessons: {
    "brent-what-it-represents": { title: "Ce que représente le Brent", explanation: "Le Brent est un pétrole de la mer du Nord dont le prix sert de référence internationale. Une grande partie du pétrole échangé est valorisée par rapport au Brent. Il s'agit de pétrole brut avant raffinage.", keyTakeaways: ["Le Brent vient de la mer du Nord.", "Il sert de référence mondiale.", "Il s'agit de pétrole brut avant raffinage."] },
    "brent-supply-demand": { title: "Offre et demande mondiales", explanation: "Le prix du pétrole réagit à l'équilibre entre l'offre mondiale et la demande liée à l'activité économique, au transport et à l'industrie. Même de petits déséquilibres peuvent faire bouger les prix.", keyTakeaways: ["Le prix dépend de l'équilibre offre/demande.", "La demande est liée à l'activité économique.", "Les déséquilibres peuvent changer rapidement."] },
    "brent-opec-geopolitics": { title: "OPEP, géopolitique et volatilité", explanation: "L'OPEP et ses partenaires coordonnent les niveaux de production. Les conflits, sanctions et instabilités dans les régions productrices peuvent aussi perturber l'offre. Cette combinaison rend le pétrole particulièrement volatil.", keyTakeaways: ["Les décisions de production peuvent déplacer les prix.", "La géopolitique peut perturber l'offre rapidement.", "Le pétrole est une matière première très volatile."] },
  }, quizQuestions: {
    "brent-q1": { question: "D'où vient le pétrole Brent ?", options: ["De la mer du Nord", "De la forêt amazonienne", "Du désert du Sahara", "Des Grands Lacs"], explanation: "Le Brent provient de champs pétroliers de la mer du Nord." },
    "brent-q2": { question: "À quoi sert le Brent ?", options: ["De référence mondiale pour le prix du pétrole", "De monnaie", "D'indice boursier", "De type d'obligation"], explanation: "Le Brent est une des principales références mondiales du prix du pétrole." },
    "brent-q3": { question: "À quoi la demande de pétrole est-elle étroitement liée ?", options: ["À l'activité économique mondiale", "Aux horaires d'ouverture de la Bourse", "Uniquement aux taux de change", "À la météo d'une seule ville"], explanation: "La demande est liée au transport, à l'industrie et à l'activité économique." },
    "brent-q4": { question: "Pourquoi de petits déséquilibres offre/demande peuvent-ils faire bouger fortement le pétrole ?", options: ["Le pétrole est central pour une grande partie de l'économie mondiale", "Le pétrole n'a aucun lien avec la demande", "Les prix ne changent jamais", "L'offre est toujours parfaitement égale à la demande"], explanation: "Le rôle central du pétrole rend les déséquilibres importants pour le prix." },
    "brent-q5": { question: "Qu'est-ce que l'OPEP ?", options: ["Un groupe de pays producteurs qui coordonne les niveaux de production", "Une Bourse mondiale", "Une banque centrale", "Une compagnie pétrolière américaine"], explanation: "L'OPEP est une organisation de pays exportateurs qui coordonne certaines décisions de production." },
    "brent-q6": { question: "Pourquoi le pétrole est-il particulièrement volatil ?", options: ["Les décisions de production et les risques géopolitiques peuvent perturber rapidement l'offre", "La demande ne change jamais", "Le pétrole n'est pas exposé aux événements mondiaux", "Les prix sont fixés une fois par an"], explanation: "Les décisions de production et les risques géopolitiques peuvent provoquer de forts changements d'offre et de prix." },
  } },
  btc: { title: "Comprendre Bitcoin", shortDescription: "Offre, sécurité du réseau, adoption, volatilité et risques réglementaires.", lessons: {
    "btc-what-it-is": { title: "Qu'est-ce que Bitcoin ?", explanation: "Bitcoin est une monnaie numérique sur un réseau décentralisé : aucune entreprise, banque ou gouvernement unique ne le contrôle. Les transactions sont enregistrées sur une blockchain publique maintenue par un réseau mondial d'ordinateurs.", keyTakeaways: ["Bitcoin est une monnaie numérique décentralisée.", "Les transactions sont enregistrées sur une blockchain publique.", "Il n'existe pas d'autorité centrale unique."] },
    "btc-supply-security": { title: "Offre et sécurité du réseau", explanation: "L'offre totale de Bitcoin est plafonnée à 21 millions. De nouveaux bitcoins sont créés progressivement par le minage et la récompense est périodiquement divisée par deux lors des halvings. Ce mécanisme contribue aussi à rendre la modification de l'historique très coûteuse.", keyTakeaways: ["L'offre totale est plafonnée à 21 millions.", "Les nouveaux coins sont créés par le minage.", "Les halvings réduisent périodiquement la récompense."] },
    "btc-adoption-risk": { title: "Adoption, volatilité et risque réglementaire", explanation: "Le prix dépend notamment de l'adoption par les particuliers, institutions et entreprises et du sentiment envers les actifs numériques. Bitcoin a historiquement été très volatil et sa réglementation varie selon les pays.", keyTakeaways: ["L'adoption et le sentiment influencent le prix.", "Bitcoin est historiquement très volatil.", "Le traitement réglementaire varie selon les pays."] },
  }, quizQuestions: {
    "btc-q1": { question: "Qui contrôle le réseau Bitcoin ?", options: ["Aucune entreprise, banque ou gouvernement unique", "Une seule banque centrale", "Une entreprise privée", "Les Nations unies"], explanation: "Bitcoin est décentralisé : aucune autorité unique ne contrôle le réseau." },
    "btc-q2": { question: "Qu'est-ce qu'une blockchain dans le contexte de Bitcoin ?", options: ["Un registre public et partagé des transactions", "Un compte bancaire", "Une pièce physique", "Une agence gouvernementale"], explanation: "La blockchain est le registre public des transactions Bitcoin." },
    "btc-q3": { question: "Quelle est l'offre maximale de Bitcoin ?", options: ["21 millions de bitcoins", "Illimitée", "1 million de bitcoins", "Elle change chaque année"], explanation: "L'offre de Bitcoin est plafonnée à 21 millions par conception." },
    "btc-q4": { question: "Que se passe-t-il lors d'un halving ?", options: ["La récompense de minage est divisée par deux", "Le plafond d'offre double", "Tous les coins sont détruits", "Les transactions sont arrêtées"], explanation: "Les halvings réduisent périodiquement la récompense des mineurs." },
    "btc-q5": { question: "Comment la volatilité de Bitcoin se compare-t-elle à celle de la plupart des actifs traditionnels ?", options: ["Elle est nettement plus élevée", "Elle est identique aux obligations d'État", "Elle est toujours plus faible", "Elle ne s'applique pas"], explanation: "Bitcoin a historiquement connu des mouvements de prix bien plus importants." },
    "btc-q6": { question: "Pourquoi la réglementation représente-t-elle un risque important pour Bitcoin ?", options: ["Le traitement varie selon les pays et évolue, ce qui peut faire bouger le prix", "Bitcoin est réglementé partout de la même manière", "La réglementation n'a aucun effet", "Un seul pays a réglementé Bitcoin"], explanation: "Les approches réglementaires diffèrent et évoluent dans le monde." },
  } },
  eth: { title: "Comprendre Ethereum", shortDescription: "Smart contracts, activité du réseau et différences entre ETH et Bitcoin.", lessons: {
    "eth-network-role": { title: "Le réseau Ethereum et le rôle d'ETH", explanation: "Ethereum est un réseau décentralisé conçu pour exécuter des programmes appelés smart contracts. ETH sert à payer les calculs du réseau via les gas fees et fonctionne aussi comme un actif pouvant être détenu ou échangé.", keyTakeaways: ["Ethereum exécute des programmes et smart contracts.", "ETH sert à payer les calculs du réseau.", "ETH est aussi un actif échangeable."] },
    "eth-smart-contracts": { title: "Smart contracts et activité du réseau", explanation: "Un smart contract est du code qui s'exécute automatiquement lorsque certaines conditions sont remplies. Chaque action nécessite des frais de gas en ETH ; une activité plus élevée peut donc accroître la demande d'ETH pour ces frais.", keyTakeaways: ["Les smart contracts sont du code auto-exécutable.", "Les actions nécessitent des frais de gas en ETH.", "L'activité du réseau est un facteur possible de demande d'ETH."] },
    "eth-competition-risk": { title: "Concurrence, évolutions et risques", explanation: "Ethereum est en concurrence avec d'autres blockchains capables d'exécuter des smart contracts. Le réseau a connu d'importantes évolutions techniques. ETH comporte aussi des risques de volatilité et de réglementation et dépend de l'activité des développeurs et utilisateurs.", keyTakeaways: ["Ethereum concurrence d'autres blockchains de smart contracts.", "Le réseau a connu des évolutions techniques importantes.", "L'activité des développeurs et utilisateurs est essentielle."] },
  }, quizQuestions: {
    "eth-q1": { question: "À quoi Ethereum est-il principalement conçu au-delà des transferts de monnaie ?", options: ["Exécuter des programmes appelés smart contracts", "Imprimer de la monnaie", "Remplacer légalement les banques", "Stocker uniquement des documents"], explanation: "Ethereum est conçu pour exécuter des smart contracts." },
    "eth-q2": { question: "À quoi servent les gas fees d'ETH ?", options: ["À payer les calculs effectués sur le réseau", "À payer une taxe", "À acheter de l'essence", "À payer internet"], explanation: "Les gas fees rémunèrent le travail informatique des transactions et smart contracts." },
    "eth-q3": { question: "Qu'est-ce qu'un smart contract ?", options: ["Du code qui s'exécute automatiquement lorsque certaines conditions sont remplies", "Un document juridique", "Un prêt bancaire", "Un contrat papier"], explanation: "Un smart contract est du code auto-exécutable sur Ethereum." },
    "eth-q4": { question: "Comment une activité plus élevée du réseau peut-elle affecter ETH ?", options: ["Elle peut augmenter la demande d'ETH pour payer les frais", "Elle n'a aucun lien", "Elle supprime toujours les frais", "Elle affecte seulement Bitcoin"], explanation: "Plus d'utilisateurs et d'applications signifie généralement plus de frais payés en ETH." },
    "eth-q5": { question: "Avec quoi Ethereum est-il en concurrence ?", options: ["D'autres blockchains capables d'exécuter des smart contracts", "Des magasins alimentaires", "Rien", "Uniquement des monnaies physiques"], explanation: "D'autres blockchains de smart contracts cherchent aussi à attirer développeurs et utilisateurs." },
    "eth-q6": { question: "De quoi dépend fortement la valeur d'Ethereum au-delà de la spéculation ?", options: ["De l'activité continue des développeurs et utilisateurs", "Uniquement du graphique", "D'une garantie gouvernementale", "Du prix de l'or"], explanation: "L'activité des développeurs et utilisateurs est centrale pour la pertinence du réseau et d'ETH." },
  } },
};

const RU: Record<string, AssetPatch> = {
  sp500: { title: "Изучаем S&P 500", shortDescription: "Что такое фондовый индекс и как работает S&P 500.", lessons: {
    "what-is-it": { title: "Что такое S&P 500?", explanation: "S&P 500 — индекс 500 крупнейших публичных компаний США и один из главных ориентиров американского рынка акций.", keyTakeaways: ["В индексе 500 крупных компаний США.", "Это индекс, а не отдельная акция."] },
    "companies-inside": { title: "Какие компании входят в индекс?", explanation: "В S&P 500 есть компании из технологий, банковского сектора, медицины, ритейла, энергетики и других отраслей.", keyTakeaways: ["Индекс охватывает много отраслей.", "Технологические гиганты — только часть индекса."] },
    "how-calculated": { title: "Как он рассчитывается?", explanation: "Индекс взвешен по рыночной капитализации: крупные компании сильнее влияют на его движение.", keyTakeaways: ["Вес зависит от капитализации.", "Крупнейшие компании имеют большее влияние."] },
    "why-price-moves": { title: "Почему его цена меняется?", explanation: "На индекс влияют прибыли компаний, ставки, инфляция и настроение инвесторов, а также ожидания экономического роста.", keyTakeaways: ["Прибыли, ставки и инфляция важны.", "Ожидания инвесторов тоже влияют."] },
    "what-it-represents": { title: "Что на самом деле представляет индекс?", explanation: "Индекс — это ориентир, а не отдельная акция. Экспозицию к S&P 500 обычно получают через фонд или ETF.", keyTakeaways: ["Индекс — ориентир, а не акция.", "Фонды и ETF могут повторять его динамику."] },
  }, quizQuestions: {
    q1: { question: "Что представляет S&P 500?", options: ["Одну компанию", "Группу крупных американских компаний", "Цену золота", "Доллар США"], explanation: "S&P 500 отслеживает 500 крупнейших компаний США." },
    q2: { question: "Как взвешен S&P 500?", options: ["Поровну", "По возрасту компаний", "По рыночной капитализации", "По алфавиту"], explanation: "Индекс взвешен по капитализации." },
    q3: { question: "Что может повлиять на S&P 500?", options: ["Изменение процентных ставок", "Погода в Нью-Йорке", "Новый эмодзи", "Ничего"], explanation: "Ставки, инфляция и прибыли компаний могут двигать индекс." },
    q4: { question: "Можно ли купить S&P 500 напрямую как одну акцию?", options: ["Да", "Нет, но существуют фонды, повторяющие его динамику", "Только банки могут", "Только за золото"], explanation: "Сам индекс не является торгуемой акцией; его динамику могут повторять фонды и ETF." },
    q5: { question: "Почему инвесторы следят за S&P 500?", options: ["Это широкий ориентир рынка США", "Он отслеживает один сектор", "Он гарантирует прибыль", "Он никогда не меняется"], explanation: "Индекс охватывает много отраслей и крупных компаний." },
  } },
  nasdaq: { title: "Изучаем Nasdaq 100", shortDescription: "Технологически ориентированный индекс роста и его отличие от S&P 500.", lessons: {
    "nasdaq-what-it-is": { title: "Что представляет Nasdaq 100?", explanation: "Nasdaq 100 отслеживает 100 крупных нефинансовых компаний Nasdaq и сильно ориентирован на технологии и рост.", keyTakeaways: ["100 крупных нефинансовых компаний.", "Сильная tech/growth-экспозиция.", "Финансовые компании исключены."] },
    "nasdaq-concentration": { title: "Концентрация, рост и волатильность", explanation: "Nasdaq 100 взвешен по капитализации, но его состав уже и более концентрирован. Поэтому несколько крупнейших компаний сильнее влияют на индекс.", keyTakeaways: ["Взвешивание по капитализации.", "Меньше отраслей — больше концентрации.", "Концентрация может усиливать движения."] },
    "nasdaq-vs-sp500": { title: "Чем он отличается от S&P 500?", explanation: "S&P 500 шире по секторам, а Nasdaq 100 сильнее сосредоточен на технологиях и росте и не включает финансовый сектор.", keyTakeaways: ["S&P 500 шире; Nasdaq 100 более tech/growth.", "Nasdaq 100 часто чувствительнее к ставкам и tech-новостям.", "Это разные срезы рынка."] },
  }, quizQuestions: {
    "nasdaq-q1": { question: "Что в основном отслеживает Nasdaq 100?", options: ["100 крупнейших нефинансовых компаний Nasdaq", "Все компании Nasdaq", "Только tech-стартапы", "Гособлигации США"], explanation: "Это выборка из 100 крупных нефинансовых компаний Nasdaq." },
    "nasdaq-q2": { question: "Какие компании исключены из Nasdaq 100?", options: ["Технологические", "Финансовые", "Потребительские", "Медицинские"], explanation: "Финансовые компании исключены из индекса." },
    "nasdaq-q3": { question: "Почему Nasdaq 100 может быть более концентрированным?", options: ["Меньше отраслей и более узкий список компаний", "В нем одна компания", "Все имеют одинаковый вес", "Он исключает крупные компании"], explanation: "Более узкий состав увеличивает вес крупнейших позиций." },
    "nasdaq-q4": { question: "Что вероятно при слабой прибыли нескольких крупнейших компаний Nasdaq 100?", options: ["Ничего", "Возможен сильный ход индекса", "Прибыль не влияет", "Реагируют только финансовые акции"], explanation: "Крупнейшие компании имеют больший вес и могут заметно двигать индекс." },
    "nasdaq-q5": { question: "Как лучше сравнить Nasdaq 100 и S&P 500?", options: ["Они одинаковы", "Nasdaq 100 шире", "Nasdaq 100 более tech/growth, S&P 500 охватывает больше отраслей", "S&P 500 исключает финансы"], explanation: "Nasdaq 100 более концентрирован на tech/growth, S&P 500 шире." },
    "nasdaq-q6": { question: "Почему Nasdaq 100 может сильнее реагировать на ставки?", options: ["В нем только облигации", "Оценки growth-компаний чувствительнее к дисконтированию будущих прибылей", "Он не связан с экономикой", "Ставки не влияют на индексы"], explanation: "Growth-компании обычно чувствительнее к ставке дисконтирования." },
  } },
  aapl: { title: "Изучаем Apple Inc.", shortDescription: "Чем владение одной компанией вроде Apple отличается от владения индексом.", lessons: {
    "aapl-business-model": { title: "Бизнес-модель Apple", explanation: "Apple продает устройства и получает растущий регулярный доход от сервисов: App Store, iCloud, Apple Music и подписок.", keyTakeaways: ["Основной бизнес — устройства.", "Сервисы создают регулярную выручку.", "Устройства и сервисы усиливают друг друга."] },
    "aapl-earnings-valuation": { title: "Выручка, прибыль и оценка", explanation: "Apple публикует выручку и прибыль. Рынок сравнивает результаты с ожиданиями и учитывает будущие прибыли при оценке акции.", keyTakeaways: ["Выручка — продажи, прибыль — результат после затрат.", "Рынок сравнивает результаты с ожиданиями.", "Цена учитывает будущие прибыли."] },
    "aapl-company-risk": { title: "Риск конкретной компании", explanation: "В индексе проблемы одной компании распределяются между другими. В одной акции Apple инвестор напрямую несет риски продукта, поставок, регулирования и спроса.", keyTakeaways: ["Отдельная акция несет специфические риски.", "Продукты, поставки и регулирование — примеры.", "Концентрация усиливает и рост, и падение."] },
  }, quizQuestions: {
    "aapl-q1": { question: "Какие две основные категории доходов есть у Apple?", options: ["Устройства и сервисы", "Реклама и розница", "Добыча и производство", "Кредиты и страхование"], explanation: "Apple зарабатывает на устройствах и сервисах." },
    "aapl-q2": { question: "Что является примером сервисного дохода Apple?", options: ["Продажи iPhone", "Подписки App Store и iCloud", "Продажи Mac", "Аренда магазинов"], explanation: "App Store и iCloud дают регулярный сервисный доход." },
    "aapl-q3": { question: "Почему акция может упасть после роста прибыли?", options: ["Рост прибыли всегда повышает цену", "Результат мог быть ниже ожиданий рынка", "Прибыль не связана с ценой", "Акция не может падать"], explanation: "Рынок оценивает результат относительно ожиданий." },
    "aapl-q4": { question: "Что примерно отражает оценка акции?", options: ["Число сотрудников", "Сколько инвесторы готовы заплатить за будущие прибыли", "Место штаб-квартиры", "Гарантированную цену"], explanation: "Оценка отражает цену за ожидаемые будущие результаты." },
    "aapl-q5": { question: "Почему одна Apple обычно рискованнее широкого индекса?", options: ["Акции всегда дороже", "Проблемы Apple не распределяются между другими компаниями", "Индексы не падают", "У Apple нет конкурентов"], explanation: "Проблемы одной компании напрямую отражаются на ее акции." },
    "aapl-q6": { question: "Что лучше всего показывает специфический риск Apple?", options: ["Общее изменение ставок", "Сбой поставок ключевой линейки", "Рост всего S&P 500", "Мировой биржевой праздник"], explanation: "Сбой поставок отдельной линейки — риск, специфичный для Apple." },
  } },
  nvda: { title: "Изучаем NVIDIA Corp.", shortDescription: "GPU, инфраструктура ИИ и риски акции с высокой скоростью роста и высокими ожиданиями.", lessons: {
    "nvda-gpus-ai": { title: "GPU и инфраструктура ИИ", explanation: "NVIDIA разрабатывает GPU, изначально созданные для графики. Их архитектура подходит для параллельных вычислений ИИ, поэтому GPU стали важной частью дата-центров.", keyTakeaways: ["Ключевой продукт NVIDIA — GPU.", "GPU подходят для вычислений ИИ.", "Важны и программные инструменты вокруг GPU."] },
    "nvda-cycle-competition": { title: "Дата-центры, цикл полупроводников и конкуренция", explanation: "Спрос на NVIDIA зависит от расходов крупных компаний на дата-центры. Полупроводники цикличны, а NVIDIA конкурирует с другими производителями и собственными чипами клиентов.", keyTakeaways: ["Спрос концентрирован у крупных клиентов.", "Полупроводники цикличны.", "Конкуренция идет с производителями и клиентскими чипами."] },
    "nvda-expectation-risk": { title: "Высокий рост и высокие ожидания", explanation: "Если цена уже учитывает сильный рост, хороший квартал может разочаровать, если лишь соответствует ожиданиям. Поэтому быстрорастущие акции чувствительны к сюрпризам.", keyTakeaways: ["Высокие ожидания могут превратить хорошие результаты в разочарование.", "Оценка зависит от будущих предположений.", "Это характерно для многих growth-компаний."] },
  }, quizQuestions: {
    "nvda-q1": { question: "Для чего изначально создавалась технология GPU NVIDIA?", options: ["Для обработки графики в играх", "Для добычи металлов", "Для таблиц", "Для электромобилей"], explanation: "GPU изначально создавались для графики." },
    "nvda-q2": { question: "Почему GPU хорошо подходят для ИИ?", options: ["Их архитектура выполняет нужные параллельные вычисления", "Они всегда самые дешевые", "Они создавались только для ИИ", "Они не потребляют электричество"], explanation: "Параллельная архитектура GPU хорошо соответствует вычислениям ИИ." },
    "nvda-q3": { question: "Что может замедлить спрос на чипы NVIDIA?", options: ["Крупные клиенты сократят расходы на дата-центры", "Ничего", "GPU станут незаконными", "Вырастет цена золота"], explanation: "Расходы крупных клиентов могут замедляться." },
    "nvda-q4": { question: "Что характерно для полупроводниковой отрасли?", options: ["Стабильный спрос", "Циклы высокого спроса и избытка предложения", "Нет конкуренции", "Гарантированный рост"], explanation: "Отрасль исторически проходит циклы дефицита и перепроизводства." },
    "nvda-q5": { question: "Почему акция может упасть после сильного роста?", options: ["Рост всегда гарантирует повышение", "Рост может лишь соответствовать уже высоким ожиданиям", "Рост не связан с ценой", "Акции реагируют только на убытки"], explanation: "При высоких ожиданиях простого соответствия прогнозу может быть недостаточно." },
    "nvda-q6": { question: "От чего зависит большая часть оценки быстрорастущей компании?", options: ["Только от прошлых результатов", "От ожиданий будущего роста", "От офисов", "Ни от чего"], explanation: "В оценке growth-компаний большую роль играют ожидания будущего." },
  } },
  tsla: { title: "Изучаем Tesla Inc.", shortDescription: "Электромобили, энергетика, ожидания роста и волатильность акции.", lessons: {
    "tsla-business-segments": { title: "Электромобили и другие направления", explanation: "Основной бизнес Tesla — электромобили. Есть также энергетика и хранение, а ожидания включают автономное вождение и робототехнику.", keyTakeaways: ["Главный источник выручки — электромобили.", "Энергетика — меньший, но реальный сегмент.", "Автономность и робототехника влияют на ожидания."] },
    "tsla-growth-competition": { title: "Ожидания роста и конкуренция", explanation: "Оценка Tesla зависит от ожиданий быстрого роста, новых продуктов и будущих направлений. Конкуренция в электромобилях также усилилась.", keyTakeaways: ["Оценка зависит от будущего роста.", "Конкуренция усиливается.", "Поставки и маржа важны для оценки роста."] },
    "tsla-volatility": { title: "Почему акция волатильна", explanation: "Высокие ожидания, публичные заявления руководства, квартальные поставки и маржа, а также неопределенные будущие бизнесы могут усиливать движения акции.", keyTakeaways: ["Ожидания усиливают реакцию на новости.", "Поставки и маржа могут сильно двигать цену.", "Часть оценки связана с будущими бизнесами."] },
  }, quizQuestions: {
    "tsla-q1": { question: "Какой сегмент дает Tesla основную выручку?", options: ["Электромобили", "Страхование", "Облачные вычисления", "Банк"], explanation: "Электромобили дают основную часть текущей выручки." },
    "tsla-q2": { question: "Что относится к энергетическому направлению Tesla?", options: ["Powerwall и Megapack", "Банк", "Социальная сеть", "Поисковик"], explanation: "Powerwall и Megapack — системы хранения энергии." },
    "tsla-q3": { question: "Что сильно выросло на рынке электромобилей?", options: ["Конкуренция", "Гарантия прибыли", "Исчезновение производителей", "Стабильность долей"], explanation: "На рынок активно выходят традиционные и новые производители." },
    "tsla-q4": { question: "Почему инвесторы следят за квартальными поставками Tesla?", options: ["Они дают сигнал о траектории роста", "Они не связаны с бизнесом", "Они важны только банкам", "Они определяют ставки"], explanation: "Поставки показывают, реализуются ли ожидания роста." },
    "tsla-q5": { question: "Почему высокие ожидания роста повышают волатильность?", options: ["Они усиливают реакцию на новости", "Они гарантируют рост", "Они устраняют риск", "Они не влияют"], explanation: "Когда рост уже заложен в цену, новости вызывают более сильные движения." },
    "tsla-q6": { question: "Что означает, что часть оценки отражает будущие непроверенные бизнесы?", options: ["Цена отражает только текущие продажи", "Часть цены основана на будущих направлениях", "Будущих планов нет", "Успех гарантирован"], explanation: "Часть оценки зависит от неопределенных будущих результатов." },
  } },
  msft: { title: "Изучаем Microsoft Corp.", shortDescription: "ПО, облако Azure, регулярная выручка и ИИ.", lessons: {
    "msft-software-cloud": { title: "ПО и облачный бизнес", explanation: "Microsoft сочетает Windows и Office с Azure, облачной платформой. Бизнес включает ПО, сервисы и инфраструктуру для компаний.", keyTakeaways: ["Microsoft сочетает ПО, сервисы и облако.", "Azure — крупный cloud-бизнес.", "Корпоративные клиенты важны."] },
    "msft-recurring-revenue": { title: "Регулярная выручка и почему она важна", explanation: "Подписки Microsoft 365 и других сервисов создают регулярные платежи и могут сделать выручку более предсказуемой, хотя риски остаются.", keyTakeaways: ["Подписки создают регулярную выручку.", "Она может быть более предсказуемой.", "Предсказуемость не устраняет риск."] },
    "msft-ai-competition": { title: "ИИ, оценка и конкуренция", explanation: "Microsoft активно инвестирует в ИИ и внедряет его в продукты и облако. Это требует больших расходов и происходит в условиях сильной конкуренции.", keyTakeaways: ["ИИ внедряется в продукты и cloud.", "ИИ требует больших инвестиций.", "Конкуренция влияет на будущие результаты."] },
  }, quizQuestions: {
    "msft-q1": { question: "Какой была историческая модель Microsoft?", options: ["Продажа ПО Windows и Office", "Продажа нефти", "Гостиницы", "Автомобили"], explanation: "Microsoft исторически выросла на продаже программного обеспечения." },
    "msft-q2": { question: "Что такое Azure?", options: ["Облачная платформа Microsoft", "Соцсеть", "Автопроизводитель", "Банк"], explanation: "Azure — облачная платформа Microsoft." },
    "msft-q3": { question: "Почему регулярная подписочная выручка более предсказуема?", options: ["Подписки создают регулярные платежи", "Гарантируют рост прибыли", "Не зависят от клиентов", "Устраняют конкуренцию"], explanation: "Регулярные платежи могут сделать выручку более предсказуемой." },
    "msft-q4": { question: "Как изменилась модель доходов Office?", options: ["В сторону регулярных подписок", "В сторону нефти", "В сторону банка", "Платежи отменены"], explanation: "Office во многом перешел на модель Microsoft 365." },
    "msft-q5": { question: "Какова реальная стоимость инвестиций Microsoft в ИИ?", options: ["Дата-центры, чипы и инфраструктура", "Никаких затрат", "Только реклама", "Магазины"], explanation: "ИИ требует инвестиций в вычисления, чипы, энергию и инфраструктуру." },
    "msft-q6": { question: "Что цена акции может отражать в отношении ИИ?", options: ["Ожидания будущих прибылей", "Только прошлую прибыль", "Расположение офисов", "Гарантированную цену"], explanation: "Цена может заранее учитывать будущие доходы и прибыль от ИИ." },
  } },
  amzn: { title: "Изучаем Amazon.com Inc.", shortDescription: "E-commerce, AWS, реклама, маржа и риски исполнения.", lessons: {
    "amzn-ecommerce-aws": { title: "E-commerce и AWS", explanation: "Amazon сочетает интернет-магазин и AWS, облачную платформу. Ритейл дает большой оборот при меньшей марже, а AWS имеет другой экономический профиль.", keyTakeaways: ["Amazon сочетает e-commerce и cloud.", "AWS — облачная платформа.", "У направлений разные профили маржи."] },
    "amzn-advertising-margins": { title: "Реклама и маржа", explanation: "Amazon продает брендам рекламу для доступа к покупателям. Поэтому инвесторы смотрят не только на общий оборот, но и на состав бизнеса и маржу.", keyTakeaways: ["Реклама дополняет ритейл и cloud.", "Разные направления имеют разную маржу.", "Состав роста важен."] },
    "amzn-execution-risk": { title: "Рост и риск исполнения", explanation: "Amazon инвестирует в несколько направлений и должен контролировать затраты и качество исполнения. Риск исполнения — возможность, что решения и инвестиции не дадут ожидаемого результата.", keyTakeaways: ["Amazon управляет несколькими направлениями.", "Инвестиции должны быть эффективно реализованы.", "Затраты и маржа важны."] },
  }, quizQuestions: {
    "amzn-q1": { question: "Что такое AWS?", options: ["Облачная платформа Amazon", "Соцсеть Amazon", "Банк", "Нефтяная компания"], explanation: "AWS — облачный бизнес Amazon." },
    "amzn-q2": { question: "Почему e-commerce обычно имеет небольшую маржу?", options: ["Логистика, запасы и конкуренция давят на маржу", "Клиенты не платят", "Онлайн-продажи бесплатны", "Маржа гарантирована"], explanation: "Логистика, доставка, запасы и конкуренция создают значительные расходы." },
    "amzn-q3": { question: "Как реклама Amazon связана с ритейлом?", options: ["Бренды платят за доступ к покупателям на платформе", "Она заменяет торговлю", "Она не связана с клиентами", "Она доступна только AWS"], explanation: "Реклама использует аудиторию и намерение покупки на платформе." },
    "amzn-q4": { question: "Почему инвесторы смотрят на структуру Amazon?", options: ["У разных направлений разная маржа и экономика", "У всех одинаковая маржа", "Выручка не важна", "AWS и ритейл одинаковы"], explanation: "Одинаковая выручка может давать разные результаты при разной марже." },
    "amzn-q5": { question: "Что означает риск исполнения у Amazon?", options: ["Риск, что решения и инвестиции не дадут ожидаемого результата", "Только биржевой риск", "Отсутствие конкуренции", "Гарантию роста"], explanation: "Речь о способности превращать решения и инвестиции в результаты." },
    "amzn-q6": { question: "Почему замедление AWS может быть важно для Amazon?", options: ["AWS — крупное направление с другой экономикой, чем ритейл", "AWS не часть бизнеса", "AWS устанавливает ставки", "AWS не приносит выручку"], explanation: "AWS существенно влияет на результаты группы." },
  } },
  googl: { title: "Изучаем Alphabet (Google)", shortDescription: "Поиск, реклама YouTube, cloud, ИИ и регуляторные риски.", lessons: {
    "googl-search-youtube": { title: "Поиск, реклама и YouTube", explanation: "Google Search и YouTube дают огромную аудиторию, которую Alphabet монетизирует рекламой. Спрос зависит от экономики, поведения пользователей и ценности рекламной аудитории.", keyTakeaways: ["Реклама дает большую часть доходов.", "Search и YouTube — ключевые рекламные платформы.", "Экономика и вовлеченность влияют на спрос."] },
    "googl-cloud-ai": { title: "Cloud и ИИ", explanation: "Google Cloud предоставляет IT-сервисы бизнесу, а ИИ внедряется в продукты Alphabet. ИИ требует дата-центров, чипов и исследований и открывает новые возможности.", keyTakeaways: ["Google Cloud предоставляет сервисы компаниям.", "ИИ внедряется в продукты.", "ИИ требует больших инвестиций."] },
    "googl-regulation-competition": { title: "Регулирование и конкуренция", explanation: "Alphabet сталкивается с вопросами конкуренции, рекламы, данных и поиска. AI-ассистенты и новые поисковые системы также могут изменить способ поиска информации.", keyTakeaways: ["Есть антимонопольное и регуляторное внимание.", "Правила данных и рекламы важны.", "ИИ может изменить поиск."] },
  }, quizQuestions: {
    "googl-q1": { question: "Какой источник доходов крупнейший у Alphabet?", options: ["Реклама", "Продажа автомобилей", "Банковские кредиты", "Добыча"], explanation: "Реклама, особенно Search и YouTube, дает основную часть доходов." },
    "googl-q2": { question: "Что влияет на спрос рекламодателей Search и YouTube?", options: ["Аудитория, намерение пользователей и экономика", "Только цена золота", "Ставки ЦБ", "Добыча нефти"], explanation: "Рекламодателям важны аудитория и пользователи, заинтересованные в предложении." },
    "googl-q3": { question: "С кем в основном конкурирует Google Cloud?", options: ["Amazon Web Services и Microsoft Azure", "Apple и Tesla", "Visa и Mastercard", "Shell и BP"], explanation: "Основные конкуренты — AWS и Microsoft Azure." },
    "googl-q4": { question: "Какова реальная стоимость инвестиций Alphabet в ИИ?", options: ["Дата-центры, чипы и исследования", "Никаких затрат", "Только офисы", "Дивиденды банков"], explanation: "ИИ требует значительных расходов на инфраструктуру и исследования." },
    "googl-q5": { question: "Почему Alphabet находится под сильным вниманием регуляторов?", options: ["Его положение в поиске, рекламе и платформах создает вопросы конкуренции и данных", "У него нет продуктов", "Tech не регулируется", "Он не занимается рекламой"], explanation: "Масштаб Alphabet привлекает антимонопольное внимание." },
    "googl-q6": { question: "Какая новая конкуренция может изменить Google Search?", options: ["AI-ассистенты и поисковые системы на базе ИИ", "Магазины одежды", "Центральные банки", "Нефтяные компании"], explanation: "AI-интерфейсы могут изменить способ поиска информации." },
  } },
  meta: { title: "Изучаем Meta Platforms", shortDescription: "Реклама, соцсети, ИИ, Reality Labs и регуляторные риски.", lessons: {
    "meta-advertising-platforms": { title: "Реклама и социальные платформы", explanation: "Meta владеет Facebook, Instagram и WhatsApp, а основная часть выручки приходит от рекламы. Рекламные бюджеты и вовлеченность пользователей напрямую влияют на результаты.", keyTakeaways: ["Facebook, Instagram и WhatsApp — основные платформы.", "Большая часть выручки — реклама.", "Рекламные бюджеты и вовлеченность важны."] },
    "meta-ai-reality-labs": { title: "ИИ и Reality Labs", explanation: "Meta инвестирует в ИИ для рекламы, рекомендаций и собственных моделей. Reality Labs создает VR/AR-продукты и исторически приносил убытки, финансируемые рекламным бизнесом.", keyTakeaways: ["ИИ поддерживает продукты и исследования.", "Reality Labs — долгосрочная VR/AR-ставка.", "Реклама исторически финансирует Reality Labs."] },
    "meta-regulatory-execution-risk": { title: "Регулирование и риск исполнения", explanation: "Meta сталкивается с вопросами конфиденциальности, конкуренции и модерации контента. Одновременно нужно финансировать дорогие направления и сохранять прибыльность рекламы.", keyTakeaways: ["Есть риски данных, конкуренции и контента.", "Несколько крупных платформ привлекают внимание антимонопольных органов.", "Баланс инвестиций и прибыльности — сложная задача."] },
  }, quizQuestions: {
    "meta-q1": { question: "Какими платформами владеет Meta?", options: ["Facebook, Instagram и WhatsApp", "YouTube и Gmail", "Amazon и AWS", "Netflix и Spotify"], explanation: "Facebook, Instagram и WhatsApp — ключевые платформы Meta." },
    "meta-q2": { question: "Какой источник доходов крупнейший у Meta?", options: ["Реклама", "Продажа оборудования", "Подписки Facebook", "Физические магазины"], explanation: "Основная часть доходов Meta приходится на рекламу." },
    "meta-q3": { question: "Что такое Reality Labs?", options: ["Подразделение Meta по VR/AR", "Рекламный отдел", "Сервис доставки", "Cloud-продукт"], explanation: "Reality Labs разрабатывает VR/AR-оборудование и ПО." },
    "meta-q4": { question: "Как исторически финансировался Reality Labs?", options: ["Прибылью рекламного бизнеса Meta", "Он всегда был прибыльным", "Госсубсидиями", "Он не требует финансирования"], explanation: "Reality Labs исторически был убыточным и финансировался рекламным бизнесом." },
    "meta-q5": { question: "Почему Meta особенно интересна антимонопольным регуляторам?", options: ["Она владеет несколькими крупными социальными платформами", "У нее нет продуктов", "Антимонопольные законы не действуют на tech", "Она работает на маленьком рынке"], explanation: "Владение несколькими крупными платформами привлекает внимание к конкуренции." },
    "meta-q6": { question: "Какой операционный вызов связан с Reality Labs?", options: ["Балансировать инвестиции в непроверенное направление и прибыльность рекламы", "Reality Labs не требует решений", "Между расходами нет напряжения", "Meta прекратила инвестиции"], explanation: "Нужно финансировать дорогую и неопределенную ставку, сохраняя прибыльность." },
  } },
  gold: { title: "Изучаем золото", shortDescription: "Что представляет золото, роль реальных ставок и отсутствие дохода от актива.", lessons: {
    "gold-what-it-represents": { title: "Что представляет золото как актив", explanation: "Золото — сырьевой и денежный актив, используемый как средство сохранения стоимости. В отличие от акции оно не дает долю в компании и не создает собственный денежный поток.", keyTakeaways: ["Золото — сырьевой актив, не доля в компании.", "Оно не создает собственный денежный поток.", "Экспозицию можно получать через финансовые продукты."] },
    "gold-inflation-real-rates": { title: "Инфляция, реальные ставки и защитный спрос", explanation: "Привлекательность золота может меняться вместе с инфляцией, реальными ставками и экономическим или геополитическим стрессом. Низкие реальные ставки снижают альтернативную стоимость актива без доходности, но не гарантируют рост цены.", keyTakeaways: ["Реальные ставки влияют на относительную привлекательность золота.", "Золото может пользоваться спросом в периоды стресса.", "Связь не гарантирует рост цены."] },
    "gold-no-earnings": { title: "Нет прибыли и дивидендов", explanation: "Золото не генерирует прибыль, дивиденды или проценты. Поэтому результат зависит от изменения цены. Это структурно отличается от акций и облигаций, которые могут приносить доход.", keyTakeaways: ["Золото не платит дивиденды и проценты.", "Результат зависит от изменения цены.", "Это отличие от акций и облигаций."] },
  }, quizQuestions: {
    "gold-q1": { question: "Платит ли золото дивиденды?", options: ["Нет", "Да, ежеквартально", "Да, только крупным инвесторам", "Только во время рецессий"], explanation: "Золото не платит дивиденды." },
    "gold-q2": { question: "Как часто получают экспозицию к золоту?", options: ["Через ETF, отслеживающий цену золота", "Через расчетный счет", "Через корпоративную облигацию", "Через арендную недвижимость"], explanation: "ETF на золото — распространенный способ получить экспозицию без хранения металла." },
    "gold-q3": { question: "Что может происходить с привлекательностью золота при низких или отрицательных реальных ставках?", options: ["Оно может стать относительно привлекательнее", "Оно всегда обесценивается", "Связи со ставками нет", "Оно начинает платить дивиденды"], explanation: "Низкие реальные ставки снижают альтернативную стоимость актива без доходности." },
    "gold-q4": { question: "Что означает спрос на золото как защитный актив?", options: ["Инвесторы обращаются к золоту в периоды стресса", "Гарантию роста в любой кризис", "Только использование в ювелирных изделиях", "Обязательную покупку государством"], explanation: "Некоторые инвесторы обращаются к золоту в периоды стресса, но рост не гарантирован." },
    "gold-q5": { question: "Если золото не приносит доход, от чего зависит результат?", options: ["От изменения цены золота", "От дивидендов", "От процентов золота", "От прибыли компании"], explanation: "Без денежного дохода результат зависит от изменения цены." },
    "gold-q6": { question: "Чем отсутствие дохода у золота отличается от акции или облигации?", options: ["Акции и облигации могут приносить доход даже без движения цены; золото — нет", "Золото приносит больше дохода", "Акции и облигации тоже не приносят доход", "Разницы нет"], explanation: "Акции могут платить дивиденды, а облигации — проценты независимо от цены." },
  } },
  "brent-oil": { title: "Изучаем нефть Brent", shortDescription: "Мировая цена нефти, спрос и предложение и высокая волатильность сырья.", lessons: {
    "brent-what-it-represents": { title: "Что представляет Brent", explanation: "Brent — нефть из Северного моря, цена которой используется как международный ориентир. Большая часть международной торговли нефтью оценивается относительно Brent.", keyTakeaways: ["Brent добывается в Северном море.", "Он служит мировым ориентиром цены.", "Это сырая нефть до переработки."] },
    "brent-supply-demand": { title: "Мировой спрос и предложение", explanation: "Цена нефти зависит от баланса мировой добычи и спроса, связанного с экономикой, транспортом и промышленностью. Даже небольшие дисбалансы могут заметно менять цену.", keyTakeaways: ["Цена зависит от мирового спроса и предложения.", "Спрос связан с экономической активностью.", "Дисбалансы могут быстро двигать цену."] },
    "brent-opec-geopolitics": { title: "ОПЕК, геополитика и волатильность", explanation: "ОПЕК и партнеры координируют добычу, а конфликты, санкции и нестабильность могут нарушать предложение. Это одна из причин высокой волатильности нефти.", keyTakeaways: ["Решения ОПЕК могут двигать цену.", "Геополитика может быстро нарушить предложение.", "Нефть особенно волатильна."] },
  }, quizQuestions: {
    "brent-q1": { question: "Откуда добывается нефть Brent?", options: ["Из Северного моря", "Из Амазонии", "Из Сахары", "Из Великих озер"], explanation: "Brent добывается на месторождениях Северного моря." },
    "brent-q2": { question: "Чем является Brent?", options: ["Мировым ориентиром цены нефти", "Валютой", "Фондовым индексом", "Облигацией"], explanation: "Brent — один из главных мировых ориентиров цены нефти." },
    "brent-q3": { question: "С чем тесно связан спрос на нефть?", options: ["С мировой экономической активностью", "С часами открытия биржи", "Только с курсами валют", "С погодой одного города"], explanation: "Спрос связан с транспортом, промышленностью и экономической активностью." },
    "brent-q4": { question: "Почему небольшие дисбалансы могут сильно двигать цену нефти?", options: ["Нефть важна для большой части мировой экономики", "Спрос не связан с нефтью", "Цены не меняются", "Предложение всегда идеально равно спросу"], explanation: "Из-за центральной роли нефти даже небольшие дисбалансы важны для цены." },
    "brent-q5": { question: "Что такое ОПЕК?", options: ["Группа нефтедобывающих стран, координирующая добычу", "Мировая биржа", "Центральный банк", "Американская нефтяная компания"], explanation: "ОПЕК — организация стран-экспортеров нефти, координирующая решения по добыче." },
    "brent-q6": { question: "Почему нефть особенно волатильна?", options: ["Решения производителей и геополитика могут быстро нарушить предложение", "Спрос никогда не меняется", "Нефть не зависит от мировых событий", "Цена устанавливается раз в год"], explanation: "Производственные решения и геополитические риски могут резко менять предложение и цену." },
  } },
  btc: { title: "Изучаем Bitcoin", shortDescription: "Предложение, безопасность сети, принятие, волатильность и регулирование.", lessons: {
    "btc-what-it-is": { title: "Что такое Bitcoin", explanation: "Bitcoin — цифровая валюта на децентрализованной сети. Транзакции записываются в публичный блокчейн, который поддерживает глобальная сеть компьютеров.", keyTakeaways: ["Bitcoin — децентрализованная цифровая валюта.", "Транзакции записываются в блокчейн.", "Нет единого центрального органа."] },
    "btc-supply-security": { title: "Предложение и безопасность сети", explanation: "Максимальное предложение Bitcoin ограничено 21 млн. Новые монеты появляются через майнинг, а награда периодически уменьшается вдвое на халвингах.", keyTakeaways: ["Максимальное предложение — 21 млн.", "Новые монеты создаются через майнинг.", "Халвинги уменьшают награду."] },
    "btc-adoption-risk": { title: "Принятие, волатильность и регуляторный риск", explanation: "Цена зависит от принятия Bitcoin и настроений вокруг цифровых активов. Исторически он значительно волатильнее большинства традиционных активов, а регулирование различается по странам.", keyTakeaways: ["Принятие и настроение влияют на цену.", "Bitcoin исторически очень волатилен.", "Регулирование различается по странам."] },
  }, quizQuestions: {
    "btc-q1": { question: "Кто контролирует сеть Bitcoin?", options: ["Ни одна отдельная компания, банк или государство", "Один центральный банк", "Одна частная компания", "ООН"], explanation: "Bitcoin децентрализован и не контролируется одной властью." },
    "btc-q2": { question: "Что такое блокчейн в контексте Bitcoin?", options: ["Публичный общий реестр транзакций", "Банковский счет", "Физическая монета", "Государственное агентство"], explanation: "Блокчейн — публичный реестр транзакций Bitcoin." },
    "btc-q3": { question: "Каково максимальное предложение Bitcoin?", options: ["21 млн монет", "Неограниченное", "1 млн монет", "Меняется каждый год"], explanation: "Протокол ограничивает предложение 21 млн монетами." },
    "btc-q4": { question: "Что происходит во время халвинга Bitcoin?", options: ["Награда за майнинг уменьшается вдвое", "Лимит предложения удваивается", "Все монеты уничтожаются", "Транзакции останавливаются"], explanation: "Халвинги периодически уменьшают награду майнеров." },
    "btc-q5": { question: "Как волатильность Bitcoin сравнивается с большинством традиционных активов?", options: ["Она значительно выше", "Она такая же, как у гос. облигаций", "Она всегда ниже", "У Bitcoin нет волатильности"], explanation: "Bitcoin исторически демонстрировал намного более крупные движения цены." },
    "btc-q6": { question: "Почему регулирование является существенным риском Bitcoin?", options: ["Подходы различаются по странам и меняются, что может двигать цену", "Bitcoin одинаково регулируется везде", "Регулирование не влияет на crypto", "Только одна страна регулировала Bitcoin"], explanation: "Регуляторные подходы различаются и меняются по всему миру." },
  } },
  eth: { title: "Изучаем Ethereum", shortDescription: "Смарт-контракты, активность сети и отличие ETH от Bitcoin.", lessons: {
    "eth-network-role": { title: "Сеть Ethereum и роль ETH", explanation: "Ethereum — децентрализованная сеть для программ и смарт-контрактов. ETH используется для оплаты вычислений через gas fees и является самостоятельным активом.", keyTakeaways: ["Ethereum запускает смарт-контракты.", "ETH оплачивает вычисления сети.", "ETH также является торгуемым активом."] },
    "eth-smart-contracts": { title: "Смарт-контракты и активность сети", explanation: "Смарт-контракт — код, который выполняется автоматически при заданных условиях. Действия в сети требуют gas fees в ETH, поэтому рост активности может увеличивать спрос на ETH.", keyTakeaways: ["Смарт-контракты — автоматически выполняемый код.", "Действия требуют gas fees в ETH.", "Активность сети может влиять на спрос на ETH."] },
    "eth-competition-risk": { title: "Конкуренция, обновления и риски", explanation: "Ethereum конкурирует с другими блокчейнами смарт-контрактов и прошел значительные технические обновления. ETH также подвержен волатильности и регуляторному риску и зависит от активности разработчиков и пользователей.", keyTakeaways: ["Ethereum конкурирует с другими blockchain-сетями.", "Сеть проходила крупные обновления.", "Активность разработчиков и пользователей важна."] },
  }, quizQuestions: {
    "eth-q1": { question: "Для чего Ethereum создан помимо обычных переводов?", options: ["Для запуска смарт-контрактов", "Для печати денег", "Для юридической замены банков", "Только для хранения документов"], explanation: "Ethereum создан для выполнения смарт-контрактов." },
    "eth-q2": { question: "Для чего используются gas fees ETH?", options: ["Для оплаты вычислений в сети", "Для государственного налога", "Для покупки бензина", "Для интернет-подписки"], explanation: "Gas fees оплачивают вычислительную работу сети." },
    "eth-q3": { question: "Что такое смарт-контракт?", options: ["Код, автоматически выполняемый при выполнении условий", "Юридический документ", "Банковский кредит", "Бумажный договор"], explanation: "Смарт-контракт — автоматически выполняемый код в Ethereum." },
    "eth-q4": { question: "Как рост активности сети может влиять на ETH?", options: ["Он может увеличить спрос на ETH для оплаты gas", "Он не связан со спросом", "Он всегда убирает комиссии", "Он влияет только на Bitcoin"], explanation: "Больше пользователей и приложений означает больше gas fees в ETH." },
    "eth-q5": { question: "С чем конкурирует Ethereum?", options: ["С другими блокчейнами смарт-контрактов", "С продуктовыми магазинами", "Ни с чем", "Только с физическими валютами"], explanation: "Другие blockchain-сети также конкурируют за разработчиков и пользователей." },
    "eth-q6": { question: "От чего зависит ценность Ethereum помимо спекуляции?", options: ["От активности разработчиков и пользователей сети", "Только от графика", "От госгарантии", "От цены золота"], explanation: "Активность разработчиков и пользователей важна для роли сети и ETH." },
  } },
};

export function getLocalizedAssetLearningPath(path: AssetLearningPath, locale: Locale): AssetLearningPath {
  if (locale === "en") return path;
  const patch = (locale === "fr" ? FR : RU)[path.assetId];
  if (!patch) return path;
  return { ...path, title: patch.title, shortDescription: patch.shortDescription,
    lessons: path.lessons.map((l) => patch.lessons[l.id] ? { ...l, ...patch.lessons[l.id] } : l),
    quizQuestions: path.quizQuestions.map((q) => patch.quizQuestions[q.id] ? { ...q, ...patch.quizQuestions[q.id] } : q) };
}

const UNLOCK_FR: Record<string, { name: string; topic: string; description: string }> = {
  sp500: { name: "S&P 500", topic: "Qu'est-ce qu'un indice de marché ?", description: "Découvrez ce qu'est un indice de marché et comment fonctionne le S&P 500." },
  nasdaq: { name: "Nasdaq 100", topic: "Croissance, technologie et volatilité", description: "Terminez le parcours S&P 500 pour débloquer l'investissement dans le Nasdaq 100." },
  aapl: { name: "Apple Inc.", topic: "Comment fonctionnent les actions individuelles", description: "Terminez le parcours Nasdaq 100 pour débloquer l'investissement dans Apple." },
  tsla: { name: "Tesla Inc.", topic: "Comprendre la volatilité et le risque propre à l'entreprise", description: "Terminez le parcours Apple pour débloquer l'investissement dans Tesla." },
  nvda: { name: "NVIDIA Corp.", topic: "Technologie, IA et semi-conducteurs", description: "Terminez le parcours Tesla pour débloquer l'investissement dans NVIDIA." },
};
const UNLOCK_RU: Record<string, { name: string; topic: string; description: string }> = {
  sp500: { name: "S&P 500", topic: "Что такое рыночный индекс?", description: "Изучите, что такое рыночный индекс и как работает S&P 500." },
  nasdaq: { name: "Nasdaq 100", topic: "Рост, технологии и волатильность", description: "Завершите курс S&P 500, чтобы открыть инвестиции в Nasdaq 100." },
  aapl: { name: "Apple Inc.", topic: "Как работают отдельные акции", description: "Завершите курс Nasdaq 100, чтобы открыть инвестиции в Apple." },
  tsla: { name: "Tesla Inc.", topic: "Понимание волатильности и специфического риска компании", description: "Завершите курс Apple, чтобы открыть инвестиции в Tesla." },
  nvda: { name: "NVIDIA Corp.", topic: "Технологии, ИИ и полупроводники", description: "Завершите курс Tesla, чтобы открыть инвестиции в NVIDIA." },
};
const ACH_FR: Record<string, { title: string; description: string }> = {
  FIRST_LESSON: { title: "Premier pas", description: "Terminez votre première leçon." }, FIRST_QUIZ: { title: "Débutant du quiz", description: "Terminez votre premier quiz." }, FIRST_INVESTMENT: { title: "Premier investissement", description: "Effectuez votre premier investissement." }, MARKET_BASICS: { title: "Bases du marché", description: "Terminez le parcours sur les fondamentaux du marché." }, INDEX_EXPLORER: { title: "Explorateur d'indices", description: "Découvrez votre premier indice de marché." }, STOCK_EXPLORER: { title: "Explorateur d'actions", description: "Découvrez votre première entreprise cotée." }, DIVERSIFIED: { title: "Diversifié", description: "Investissez dans au moins 3 actifs différents." }, SEVEN_DAY_STREAK: { title: "Série de 7 jours", description: "Apprenez pendant 7 jours consécutifs." },
};
const ACH_RU: Record<string, { title: string; description: string }> = {
  FIRST_LESSON: { title: "Первый шаг", description: "Завершите свой первый урок." }, FIRST_QUIZ: { title: "Начало викторин", description: "Завершите свою первую викторину." }, FIRST_INVESTMENT: { title: "Первая инвестиция", description: "Совершите первую инвестицию." }, MARKET_BASICS: { title: "Основы рынка", description: "Завершите базовый курс по устройству рынка." }, INDEX_EXPLORER: { title: "Исследователь индексов", description: "Изучите свой первый рыночный индекс." }, STOCK_EXPLORER: { title: "Исследователь акций", description: "Изучите свою первую отдельную компанию." }, DIVERSIFIED: { title: "Диверсификация", description: "Инвестируйте как минимум в 3 разных актива." }, SEVEN_DAY_STREAK: { title: "Серия 7 дней", description: "Учитесь 7 дней подряд." },
};

export function getLocalizedUnlockText(assetId: string, locale: Locale) {
  if (locale === "en") return undefined;
  return (locale === "fr" ? UNLOCK_FR : UNLOCK_RU)[assetId];
}
export function getLocalizedAchievementText(id: string, locale: Locale) {
  if (locale === "en") return undefined;
  return (locale === "fr" ? ACH_FR : ACH_RU)[id];
}
